if (CMAKE_SYSTEM_PROCESSOR MATCHES "i386|i686|x86|x86_64|x64|amd64|AMD64|win32|Win32")
    set(IS_X86 TRUE)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|x64|amd64|AMD64")
        set(IS_X64 TRUE)
    endif()
endif()
if (CMAKE_SYSTEM_PROCESSOR MATCHES "arm|ARM|aarch64|arm64|ARM64|armeb|aarch64be|aarch64_be")
    set(IS_ARM TRUE)
endif()
if (CMAKE_SYSTEM_PROCESSOR MATCHES "riscv64|rv64")
    set(IS_RISCV64 TRUE)
endif()
if (CMAKE_SYSTEM_PROCESSOR MATCHES "riscv32|rv32")
    set(IS_RISCV32 TRUE)
endif()

add_compile_definitions(HAVE_CONFIG_H PARPAR_ENABLE_HASHER_MD5CRC)

if(WIN32)
    if(BUILD_LIB)
        target_compile_definitions(${PAR2_LIBRARY} PRIVATE UNICODE)
    endif()

    if(BUILD_TOOL)
        target_compile_definitions(${PACKAGE} PRIVATE UNICODE)
        target_compile_definitions(${PACKAGE} PRIVATE CONSOLE)
    endif()
endif()

if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|AppleClang")
        add_compile_options(-Weverything)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        add_compile_options(-Wall -Wextra)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        add_compile_options(/Od /Zi /MTd /MP /W4)
    endif()
elseif(${CMAKE_BUILD_TYPE} STREQUAL "Release")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        add_compile_options(/O2 /Oi /GS /MP)
        add_link_options(/OPT:REF /OPT:ICF)
    else()
        add_compile_options(-fstack-protector-strong -Wno-unused-function)
    endif()
endif()
